on:
  push:
    branches:
      - "main"

defaults:
  run:
    shell: bash

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  deploy_ec2:
    name: terraform🚀
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: init
        run: |
          terraform init

      - name: validate
        run: |
          terraform fmt
          terraform validate

      - name: plan
        run: |
          echo $AWS_ACCESS_KEY_ID
          terraform plan
